/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber';
import { Group, Object3DEventMap } from 'three';


export function Criminal(props: Partial<GroupProps>) {
  const group = useRef<Group<Object3DEventMap>>();
  const { nodes, materials } = useGLTF('/models/player.gltf');

  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group>
        <primitive object={nodes.LeftFootCtrl} />
        <primitive object={nodes.RightFootCtrl}/>
        <primitive object={nodes.HipsCtrl} />
        <skinnedMesh
          castShadow
          geometry={nodes.characterMedium.geometry}
          material={materials['skin.001']}
          receiveShadow
          skeleton={nodes.characterMedium.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/player.gltf');