// import { KeyboardControls, useFBX, useTexture } from "@react-three/drei";
// import Ecctrl from 'ecctrl';

// export function Player() {
//   const texture = useTexture('/textures/criminalMaleA.png');
//   const fbx = useFBX('/models/characterMedium.fbx');
//   fbx.traverse((child) => {
//     if (child.isMesh) {
//       child.material.map = texture;
//     }
//   });

//   return <KeyboardControls map={[
//     { name: "forward", keys: ["ArrowUp", "KeyW"] },
//     { name: "backward", keys: ["ArrowDown", "KeyS"] },
//     { name: "leftward", keys: ["ArrowLeft", "KeyA"] },
//     { name: "rightward", keys: ["ArrowRight", "KeyD"] },
//     // { name: "jump", keys: ["Space"] },
//     // { name: "run", keys: ["Shift"] },
//     // Optional animation key map
//     { name: "action1", keys: ["1"] },
//     { name: "action2", keys: ["2"] },
//     { name: "action3", keys: ["3"] },
//     { name: "action4", keys: ["KeyF"] },
//   ]}>
//     <Ecctrl
//       accDeltaTime={1.0}
//       // capsuleHalfHeight={0.035}
//       // capsuleRadius={0.1}
//       maxVelLimit={1.2}
//       moveImpulsePointY={0.0}
//       turnSpeed={1000}

//     >
//       <mesh castShadow receiveShadow>
//         <primitive
//           object={fbx}
//           scale={0.0015}
//           position={[0, 0, 0]}
//         />;
//         <meshToonMaterial map={texture} />
//         {/* <meshPhongMaterial map={texture}/> */}
//         {/* <meshStandardMaterial map={texture}/> */}
//       </mesh>
//     </Ecctrl>
//   </KeyboardControls>
// }

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber';
import { Group, Object3DEventMap } from 'three';


export function Character(props: Partial<GroupProps>) {
  const group = useRef<Group<Object3DEventMap>>();
  const { nodes, materials } = useGLTF('/models/player.gltf');

  return (
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group scale={0.65} >
        <primitive object={nodes.LeftFootCtrl} />
        <primitive object={nodes.RightFootCtrl} />
        <primitive object={nodes.HipsCtrl} />
        <skinnedMesh
          castShadow
          geometry={nodes.characterMedium.geometry}
          material={materials['skin.001']}
          skeleton={nodes.characterMedium.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/male/model.gltf');